#!/bin/bash -eux
source "$(dirname $0)/bin/conf"

[ "$USER" = "root" ] # USER MUST BE ROOT

### PULL DATA ###
rm -fr "${contentsdir:?}"
cd "$wwwdir"
git clone "https://github.com/$contens_owner/$contents"
chown www-data:www-data "contentsdir" -R
