#!/bin/bash -eux
source "$(dirname $0)/bin/conf"

[ "$USER" = "root" ] # USER MUST BE ROOT

#### CREATE DIRECTORIES ###
mkdir -p "$logdir" "$datadir"
chown nginx:nginx "$logdir" "$datadir"

### INSTALL THIS SYSTEM ###
rsync -av --delete "$(dirname $0)/bin/" "$appdir/"
chown nginx:nginx "$appdir" -R

### RENAME FETCH CGI ###
cd "$appdir"
rnd=$(cat /dev/urandom | tr -cd 0-9a-zA-Z | head -c 32)
[ -e "/home/ueda/rnd"] && rnd=$(cat /home/ueda/rnd ) # REMOVE ON RELEASE!!
mv "fetch" "fetch_$rnd.cgi"

### PULL DATA ###
rm -fr "${contentsdir:?}"
cd "$wwwdir"
git clone "https://github.com/$contents_owner/$contents"
chown nginx:nginx "$contentsdir" -R

echo "call fetch fetch_$rnd.cgi from GitHub"
